format_version: v1.0
type: UniqueComponent
attributes: {id: sys_fs}
children:
- type: Symbols
  children:
  - type: Menu
    attributes: {id: MEDIA_CONF_MENU0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: SYS_FS_AUTO_MOUNT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: SYS_FS_CLIENT_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: SYS_FS_DISKIO_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /system/fs/fat_fs/v0.14/hardware_access/diskio.h}
  - type: File
    attributes: {id: SYS_FS_DISKIO_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /system/fs/fat_fs/v0.14/hardware_access/diskio.c.ftl}
  - type: KeyValueSet
    attributes: {id: SYS_FS_FAT_CODE_PAGE}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: All, value: '0', key: CODE_PAGE_0}
          - type: Pair
            attributes: {description: U.S., value: '437', key: CODE_PAGE_437}
          - type: Pair
            attributes: {description: Arabic, value: '720', key: CODE_PAGE_720}
          - type: Pair
            attributes: {description: Greek, value: '737', key: CODE_PAGE_737}
          - type: Pair
            attributes: {description: KBL, value: '771', key: CODE_PAGE_771}
          - type: Pair
            attributes: {description: Baltic, value: '775', key: CODE_PAGE_775}
          - type: Pair
            attributes: {description: Latin 1, value: '850', key: CODE_PAGE_850}
          - type: Pair
            attributes: {description: Latin 2, value: '852', key: CODE_PAGE_852}
          - type: Pair
            attributes: {description: Cyrillic, value: '855', key: CODE_PAGE_855}
          - type: Pair
            attributes: {description: Turkish, value: '857', key: CODE_PAGE_857}
          - type: Pair
            attributes: {description: Portuguese, value: '860', key: CODE_PAGE_860}
          - type: Pair
            attributes: {description: Icelandic, value: '861', key: CODE_PAGE_861}
          - type: Pair
            attributes: {description: Hebrew, value: '862', key: CODE_PAGE_862}
          - type: Pair
            attributes: {description: Canadian French, value: '863', key: CODE_PAGE_863}
          - type: Pair
            attributes: {description: Arabic, value: '864', key: CODE_PAGE_864}
          - type: Pair
            attributes: {description: Nordic, value: '865', key: CODE_PAGE_865}
          - type: Pair
            attributes: {description: Russian, value: '866', key: CODE_PAGE_866}
          - type: Pair
            attributes: {description: Greek 2, value: '869', key: CODE_PAGE_869}
          - type: Pair
            attributes: {description: Japanese (DBCS), value: '932', key: CODE_PAGE_932}
          - type: Pair
            attributes: {description: Simplified Chinese (DBCS), value: '936', key: CODE_PAGE_936}
          - type: Pair
            attributes: {description: Korean (DBCS), value: '949', key: CODE_PAGE_949}
          - type: Pair
            attributes: {description: Traditional Chinese (DBCS), value: '950', key: CODE_PAGE_950}
  - type: File
    attributes: {id: SYS_FS_FAT_CONF_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /system/fs/fat_fs/v0.14/file_system/ffconf.h.ftl}
  - type: File
    attributes: {id: SYS_FS_FAT_HEADER}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: /system/fs/fat_fs/v0.14/file_system/ff.h}
  - type: File
    attributes: {id: SYS_FS_FAT_SOURCE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: system/fs/fat_fs/v0.14/file_system/ff.c}
  - type: Combo
    attributes: {id: SYS_FS_FAT_VERSION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: v0.14}
  - type: Integer
    attributes: {id: SYS_FS_MAX_FILES}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25'}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_1_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda1}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_2_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda2}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_3_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda3}
  - type: String
    attributes: {id: SYS_FS_MEDIA_DEVICE_4_NAME_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: /dev/sda4}
  - type: Combo
    attributes: {id: SYS_FS_MEDIA_TYPE_DEFINE_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SYS_FS_MEDIA_TYPE_MSD}
  - type: Integer
    attributes: {id: SYS_FS_TOTAL_VOLUMES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_fs, value: '1'}
  - type: Integer
    attributes: {id: SYS_FS_VOLUME_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: sys_fs_DRV_MEDIA_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: usb_host_msd, targetAttachmentID: USB Host
            MSD}
- type: ElementPosition
  attributes: {x: '439', y: '364', id: sys_fs}
