format_version: v1.0
type: UniqueComponent
attributes: {id: nvmctrl}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvmctrl, value: '5'}
- type: ElementPosition
  attributes: {x: '633', y: '105', id: nvmctrl}
