configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: audio;azure-rtos-threadx;azure_rtos_demos;bsp;bt;core;crypto;cryptoauthlib;csp;csp_apps_sam_9x60;gfx;motor_control;net;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_9x60;net_apps_sam_a5d2;net_apps_sam_e5x;net_apps_sam_e70_v71;net_apps_sam_rh71;usb;wireless;wireless_wifi;zzz_expresslogic_threadx
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.5.87\atdf\ATSAME54P20A.atdf
