format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E54_Xplained_Pro, bsp: 'true'}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_CUSTOM_IE3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'True'}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED1}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: LED2}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SWITCH}
  - type: String
    attributes: {id: BSP_CUSTOM_TYPE3}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SWITCH1}
- type: ElementPosition
  attributes: {x: '611', y: '19', id: BSP_SAM_E54_Xplained_Pro}
