format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipHttpNet}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_HTTP_NET_CUSTOM_TEMPLATE_SL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: 'true'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipHttpNet, value: '4944'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_LISTEN_PORT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '443'}
  - type: Integer
    attributes: {id: TCPIP_HTTP_NET_SSI_VARIABLE_STRING_MAX_LENGTH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: String
    attributes: {id: TCPIP_HTTP_NET_WEBPAGE_DIRECTORY_PATH}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'D:\microchip\h3\net\web_pages'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: auth.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/auth.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: cookies.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/cookies.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE10}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: mchp.gif}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/mchp.gif'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE11}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: mchp.js}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/mchp.js'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE12}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: snmp.bib}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/snmp.bib'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE13}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: ssi.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/ssi.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE14}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: status.xml}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/status.xml'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE15}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: upload.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/upload.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE16}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: dyndns\index.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\dyndns\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/dyndns/index.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE17}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: email\index.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\email\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/email/index.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE18}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: protect\config.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\protect\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/protect/config.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE19}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: protect\index.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\protect\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/protect/index.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: dynvars.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/dynvars.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE20}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: protect\reboot.cgi}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\protect\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/protect/reboot.cgi'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE21}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: protect\reboot.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\protect\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/protect/reboot.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE22}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: ../../web_pages}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: snmp\snmpconfig.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\snmp\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/snmp/snmpconfig.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE23}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: dest}
        children:
        - {type: Value, value: ../../web_pages}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: snmp\snmpconfig.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: test_pages\snmp\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: test_pages/snmp/snmpconfig.htm}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE3}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: footer.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/footer.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE4}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: forms.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/forms.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE5}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: harmony.gif}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/harmony.gif'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE6}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: header.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/header.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: index.htm}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/index.htm'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE8}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: leds.cgi}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/leds.cgi'}
  - type: File
    attributes: {id: WEBPAGE_LIST_FILE9}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
      - type: String
        attributes: {id: name}
        children:
        - {type: Value, value: mchp.css}
      - type: String
        attributes: {id: project}
        children:
        - {type: Value, value: web_pages\}
      - type: String
        attributes: {id: source}
        children:
        - {type: Value, value: 'D:/microchip/h3/net/web_pages/mchp.css'}
- type: ElementPosition
  attributes: {x: '30', y: '60', id: tcpipHttpNet}
