format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipSmtpc}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: TCPIP_SMTPC_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipSmtpc, value: '352'}
  - type: Boolean
    attributes: {id: TCPIP_SMTPC_USE_MAIL_COMMAND}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '250', y: '140', id: tcpipSmtpc}
